digidentity/libsaml

lib/saml/provider.rb, spec/lib/saml/provider_spec.rb
Added the ability to easily retrieve a default AssertionConsumerService or the AssertionConsumerService specified by its index.
=> Retrieve the AssertionConsumerService by index or if it isn't specified retrieve the default.

lib/saml.rb, lib/saml/elements/md_extensions.rb, lib/saml/elements/publication_info.rb, spec/factories/all.rb, spec/lib/saml/elements/md_extensions_spec.rb, spec/lib/saml/elements/publication_info_spec.rb
Added the PublicationInfo element including its mdrpi (Metadata Extensions for Registration and Publication Information) namespace.
=> Add metadata publication info extension

lib/saml.rb, lib/saml/elements/session_index.rb, lib/saml/logout_request.rb, spec/factories/all.rb, spec/fixtures/logout_request.xml, spec/lib/saml/elements/session_index_spec.rb, spec/lib/saml/logout_request_spec.rb
The optional SessionIndex element may be needed by some IDPs; this patch allows for that element to be included in LogoutRequests.
See: https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf LINE 2545
=> Allows for the optional specification of SessionIndex in LogoutRequest

lib/saml/base.rb, spec/lib/saml/base_spec.rb
We need this since one of the IDPs we talk to requires something like `<ds:Reference URI="">`.
=> Allowing blank attributes to be set on Saml::Base.

lib/saml/bindings/http_artifact.rb, lib/saml/util.rb, spec/lib/saml/bindings/http_artifact_spec.rb, spec/lib/saml/bindings/soap_spec.rb, spec/lib/saml/util_spec.rb
Our application requires the use of a proxy to resolve HTTP artifacts. We would like to avoid setting the `http_proxy` environment variable to achieve this. I've modified `HTTPArtifact#resolve` to also take in `additional_headers` and `proxy` arguments. This should not break existing code.
=> Add proxy option for HTTP artifact resolution

CHANGELOG.md, lib/saml/assertion.rb, lib/saml/elements/subject.rb, lib/saml/version.rb, spec/lib/saml/assertion_spec.rb, spec/lib/saml/elements/subject_spec.rb
Subject does not create an empty NameID anymore when no name_id is given.
Bumped version and updated changelog.
=> Added option to add a custom subject to an Assertion.

CHANGELOG.md, lib/saml/config.rb, lib/saml/util.rb, lib/saml/version.rb, spec/lib/saml/config_spec.rb, spec/lib/saml/util_spec.rb
- The private key can now be configured by #ssl_private_key which must be an OpenSSL::PKey::RSA.
- The certificate can now be configured with #ssl_certificate which must be an OpenSSL::X509::Certificate.
The existing #ssl_private_key_file and #ssl_certificate_file methods are only used to set the private key and certificate.
=> Add #ssl_private_key and #ssl_certificate_file to the Config.

lib/saml/bindings/http_redirect.rb
Signature verification for any `SAMLResponse` always fails because the wrong key was read from `request.params`.
I didn't add any tests because it seems a little silly just to duplicate the whole suite of tests for `HTTPRedirect` for responses instead of only requests.
=> Fixed HTTP-Redirect signature verification always using SAMLRequest

lib/saml/provider.rb, spec/lib/saml/provider_spec.rb
We are using libsaml in a rails app with a database connection through the `pg` gem.  When saml signature verification fails, it leaves an error in the current thread's OpenSSL error queue, which can cause the `pg` gem to throw an exception.
See https://bugs.ruby-lang.org/issues/7215 for more detailed information.
The workaround is to call `OpenSSL.errors`, which calls https://www.openssl.org/docs/manmaster/crypto/ERR_get_error.html in succession until the error queue is cleared (https://github.com/ruby/ruby/blob/trunk/ext/openssl/ossl.c#L363).
It's possible that this is a backward incompatible change if any users are relying on `OpenSSL.errors` to inspect the verification errors, as subsequent calls to `OpenSSL.errors` will be empty now.
However, I believe if those users need a method …
=> Make sure the OpenSSL error queue is cleared after failed certificate signature verification

lib/saml/bindings/http_redirect.rb, spec/lib/saml/bindings/http_redirect_spec.rb
Thanks for the quick review and merge of my last PR 😄.  Here is another small code change to get libsaml working with Google's IDP.  When integrating with Google, the SSO url has an existing query parameter (https://accounts.google.com/o/saml2/idp?idpid=xxx), which causes an error due to the `SAMLRequest` parameter being appended with a `?` instead of a `&`.
This PR changes the redirect url creation to check for existing parameters, and append the SAML parameters with the correct delimiter.
=> change delimiter for appending url parameters in redirect if existing parameters are present

lib/saml/bindings/http_post.rb
Redirect binding allows non-signed AuthN Request, but POST binding doesn't.
This change allows such request in POST binding too.
=> accept non-signed saml authn request when it's allowed explicitly

lib/saml/assertion.rb, lib/saml/authn_request.rb, lib/saml/complex_types/request_abstract_type.rb
Replaced deprecated style to lambda.
ref.) https://github.com/rails/rails/blob/master/activesupport/CHANGELOG.md#rails-510beta1-february-23-2017
=> Passing string to :if and :unless conditional options on callbacks is deprecated in Rails 5.1.

saml.gemspec
We want to upgrade our application to Nokogiri 1.7.1, but xmldsig 0.5.y version has tied it to 1.6.y. We have no problems with the 0.6.y versions (breaking change is default to SHA256 hash). Since xmldsig is still in the 0.x version scheme, I put the upper limit to one minor version higher.
BTW, this file is committed with Windows line endings
=> Also allow 0.6.y versions of xmldsig

CHANGELOG.md, lib/saml/elements/encrypted_id.rb, lib/saml/version.rb, saml.gemspec, spec/lib/saml/elements/encrypted_id_spec.rb
"In scenarios where the encrypted element is being “multicast” to multiple recipients, and the key used to encrypt the message must be in turn encrypted individually and independently for each of the multiple recipients, the <xenc:CarriedKeyName> element SHOULD be used to assign a common name to each of the <xenc:EncryptedKey> elements so that a <ds:KeyName> can be used from within the <xenc:EncryptedData> element’s <ds:KeyInfo> element."
=> Sign encrypted data with multiple recipients

lib/saml/basic_provider.rb
The signing key already defaults to the encryption key, so this should be safe.
Also see discussion in https://github.com/digidentity/libsaml/commit/b745646c33f3ba70da1fd1f98a501e143347a6f1
=> Backward compatibility fix.

lib/saml/encoding.rb, spec/lib/saml/bindings/http_redirect_spec.rb
This is a pull request for #152
=> Remove all whitespace and linefeeds in base64 encoded parts in URL

lib/saml/assertion.rb, spec/lib/saml/assertion_spec.rb
Hi,
I'm developing an SAML IdP which also support Shibboleth.
In that use-case, I need these option.
Cheers
=> allow specifying NameFormat & FriendlyName at Saml::Assertion#add_attribute

lib/saml/assertion.rb, lib/saml/elements/attribute_value.rb, lib/saml/elements/name_id.rb, spec/lib/saml/assertion_spec.rb
NameId#SPNameQualifier and AttributeValue#NameId is needed for Shibboleth's "eduPersonTargetedID" attribute.
ref.) https://www.switch.ch/aai/support/documents/attributes/edupersontargetedid/
=> NameId#SPNameQualifier and AttributeValue#NameId for Shibboleth support

lib/saml.rb, lib/saml/authn_request.rb, lib/saml/elements/name_id_policy.rb, spec/fixtures/authn_request_with_name_id_policy.xml, spec/lib/saml/authn_request_spec.rb
For certain IDP provider, `NameIDPolicy` might be required for AuthnRequest, such as Novell NIDP in my case. I have to make sure this element present to make sure SSO can work. So I added two options for AuthnRequest to allow initialize AuthnRequest with `NameIDPolicy` element, two properties will need to be passed: `format` and `allow_create`, this element will only be created if `format` property has been passed.  Usage is pretty straight forward:
```ruby
authn_request = Saml::AuthnRequest.new(destination: sso_desitination,
assertion_consumer_service_url: callback_url,
name_id_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
allow_create: true)
```
The above codes will insert following element in AuthnRequest:
```xml
<samlp:NameIDPolicy AllowCreate="true" …
```
=> Support NameIDPolicy element in AuthnRequest

lib/saml/bindings/soap.rb
When using O365's ECP feature, O365 sends unsigned SOAP request to IdP's ECP endpoint.
So that this pull request allows it.
ps.
ECP is required to receive emails on mail clients which doesn't support SAML WebSSO profile (e.g., Thuderbird, Android Gmail app)
ref.) https://github.com/digidentity/libsaml/issues/159
=> allow non-signed AuthnRequest for O365 ECP use-case.

lib/saml/response.rb, lib/saml/util.rb, spec/lib/saml/util_spec.rb
Hi, one of my client's SP requires SP certificate in the response's encrypted assertion.
I've added it and updated related specs.
ps.
This change increase the response size a bit.
If you don't like it, I can make the certificate optional.
=> optionally include SP certificate in encrypted assertions

lib/saml/bindings/http_redirect.rb, spec/lib/saml/bindings/http_redirect_spec.rb
In my use case, AuthnRequest doesn't need to be signed. 
Our IdP is Azure which said the following:
https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-saml-protocol#signature
> Signature
Don't include a Signature element in AuthnRequest elements, as Azure AD does not support signed authentication requests.
Besides, by making AuthnRequest optional, when adding service-provider to provider store, we don't need to specify a signing key.
https://github.com/digidentity/libsaml/issues/168#issuecomment-586922207
- Added instance variable `exclude_signature`, defined by `options[:exclude_signature]`
- Existing applications which are not specifying this option will run as usual (sign AuthnRequest and add Signature, SigAlg params in AuthnRequest URL)
- Will not sign and …
=> Make AuthnRequest Signature and SigAlg optional

lib/saml/assertion.rb, lib/saml/elements/authn_statement.rb, spec/fixtures/artifact_response.xml, spec/lib/saml/assertion_spec.rb
Add `SessionNotOnOrAfter` attribute to `Saml::Elements::AuthnStatement`.
From SAML core spec [2.7.2](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf):
> SessionNotOnOrAfter [Optional]
>
> Specifies a time instant at which the session between the principal identified by the subject and the SAML authority issuing this statement MUST be considered ended. The time value is encoded in UTC, as described in Section 1.3.3.
This solve #172
=> Add SessionNotOnOrAfter attribute to Saml::Elements::AuthnStatement

lib/saml.rb, lib/saml/bindings/http_post.rb, spec/lib/saml/bindings/http_post_spec.rb
Thanks for creating a great gem.
I created this PR because I found one problem while developing a project using this gem. Please check if you like.
If both `SAMLRequest` and` SAMLResponse` are nil in the request parameter, the argument `nil` is specified in` Saml::Encoding#decode_64` and the exception `NoMethodError` is raised.
```
$ Saml::Encoding.decode_64(nil)
NoMethodError: undefined method `unpack1' for nil:NilClass
from /usr/local/lib/ruby/2.7.0/base64.rb:59:in `decode64'
```
See: https://github.com/digidentity/libsaml/blob/master/lib/saml/bindings/http_post.rb#L23
This isn't friendly to developers, so I've added an exception class `Saml::Errors::InvalidParams` to detect this.
=> Add invalid params error handling for `Saml::Bindings::HTTPPost.receive_message`

lib/saml/bindings/http_redirect.rb, spec/lib/saml/bindings/http_redirect_spec.rb
`Saml::Bindings::HTTPRedirect.receive_message` decodes the request parameter` SAMLRequest` or `SAMLResponse`, but if neither exists, it becomes` nil`. Then, `nil` is specified in the argument of Saml :: Encoding.decode_64` method, and the following error occurs.
```
$ Saml::Encoding.decode_64(nil)
NoMethodError: undefined method `unpack1' for nil:NilClass
from /usr/local/lib/ruby/2.7.0/base64.rb:59:in `decode64'
```
This error isn't kind to the developer, so I've added a process to check that the input parameter has a `SAMLRequest` or` SAMLResponse` and raise an exception if it doesn't.
This is similar to the next PR. https://github.com/digidentity/libsaml/pull/176
=> Add invalid params error handling for `Saml::Bindings::HTTPRedirect.receive_message`

Gemfile, lib/saml/provider.rb, spec/lib/saml/provider_spec.rb
SHA512 signed SAML requests were causing invalid signature errors.
=> Added support for SHA512

lib/saml/bindings/http_post.rb, spec/lib/saml/bindings/http_post_spec.rb
some SP want assertions signed, and responses not signed.
(eg. OBC Bugyou Cloud, one of the biggest accounting SaaS software in Japan)
=> skip_signature option on Saml::Bindings::HTTPPost#create_form_attributes

lib/saml/util.rb, spec/lib/saml/util_spec.rb
Util#verify_xml should raise Saml::Errors::SignatureMissing when signed node is missing
Originally, "NoMethodError: undefined method `canonicalize' for nil:NilClass" had been raised.
It could reproduced when you've setup Google Workspace without "signed response" mode off.
=> raise Saml::Errors::SignatureMissing when Response element is not signed
